### ISSUE TITLE
CV_Gate16: ability to 'lock' certain vaues?

### ISSUE THREAD

**Issue by mxmilkiib** [ryukau/LV2Plugins#14]
Could it be possible to have a mechanism to 'lock' an output value, maybe like a middle-click on it, greying out the strip, so that left mouse clicks and drags don't affect it?

**Comment by ryukau** [comment]
Lock functionality is added. Check out `barboxlock` branch and let me know if it works as you intended.

To toggle lock/unlock, use <kbd>Shift</kbd>+ <kbd>Mouse Right Drag</kbd>.

Line edit uses the state of bar below cursor when right mouse button (RMB) is pressed. For example, if RMB is pressed on locked bar, line edit activates bars while holding down RMB.

**Comment by mxmilkiib** [comment]
Thank you, this works, though one cannot tell when a bar with a value of 0 is locked.

**Comment by ryukau** [comment]
Added lock indicator on `barboxlock` branch.

Maybe visibility of lock indicator can be improved. I tried overlay for locked bar, but it felt too crowded because there are already text and mouse focus overlay.

**Comment by ryukau** [comment]
Merged `barboxlock` to `master`.
