### ISSUE TITLE
CV_Gate16: Trigger outputs with a delay don't fire

### ISSUE THREAD

**Issue by mxmilkiib** [ryukau/LV2Plugins#18]
When outputs are set to Gate and have a delay, a held MIDI note triggers the gates opening, but the same channels set instead to Trigger do not fire a trigger after a time when a MIDI note is held on.

**Comment by ryukau** [comment]
Thanks for the catch. Fixed in latest commit.

If it's not working as intended, feel free to reopen this issue.

**Comment by mxmilkiib** [comment]
Thank you! Btw though, I don't have the option to reopen this issue.

**Comment by ryukau** [comment]
Ah sorry, I didn't know that. I will change the phrase in future.

Just in case, I'm notified all comments on this repo via email. So if there's something to add for closed issue, please add a comment to it.
