### ISSUE TITLE
CV_Gate16: ability to only edit one value at a time?

### ISSUE THREAD

**Issue by mxmilkiib** [ryukau/LV2Plugins#26]
So like holding a key before clicking-and-holding on the value and as long as the key is held the mouse pointer can go any horizontal direction whilst still changing that one value bar depending on vertical position.

**Comment by ryukau** [comment]
Currently, shortcut for mouse button runs out.

VST 3 version uses <kbd>Mouse R</kbd> to open context menu provided by host. In this repo, I'm preserving <kbd>Mouse M</kbd> to keep feature parity between LV2 and VST 3.

I avoided <kbd>Alt</kbd> because desktop manager in Linux tends to have shortcut with <kbd>Alt</kbd>.

Perhaps <kbd>Shift</kbd> + <kbd>Mouse R</kbd> or <kbd>Ctrl</kbd> + <kbd>Mouse R</kbd> can be altered. Are you using these shortcut?

**Comment by mxmilkiib** [comment]
No, I'm not using those.

**Comment by ryukau** [comment]
Then I'll change one of them. Thanks for the answer.

**Comment by ryukau** [comment]
Changed <kbd>Shift</kbd> + <kbd>Mouse Right Drag</kbd> to only edit one bar while holding down mouse right button.

Please let me know if it works as you intended.

**Comment by mxmilkiib** [comment]
Yes, that works much better.

Though; if I click left and drag around, the bars all change ok, but f I hold right click down (without shift) and drag around, it goes very slow and the number stops updating for a short few seconds.

**Comment by ryukau** [comment]
Slow down is not occurring on my environment. Could you change the variable in line 62 of `common/gui/barbox.hpp` to `false` and test again?

```c++
bool liveUpdateLineEdit = false; // Set this false when line edit is slow.
```

**Comment by mxmilkiib** [comment]
That fixes the stutter, when the pointer is right click-dragged above one channel that channel is moved at half(?) the rate to the left click drag, when it's above others it draws the straight line from that origin point.

**Comment by ryukau** [comment]
That's working as intended, however the behavior may be improved.

Line edit is working as the top figure in the image below. When right button is down, that position is stored as anchor. After that, it draws line between the anchor and mouse cursor.

If the anchor and mouse cursor is on the same bar region, then BarBox sets the mid point of the line as new value. The bottom figure in the image below shows this behavior.

![barbox_line_edit_single_bar](https://user-images.githubusercontent.com/6243462/87612109-a2210d00-c744-11ea-821a-461dd1ad67fa.png)

There's 2 alternatives when anchor and cursor is on the same bar: Setting the value to the cursor position, or the anchor position.

To change behavior, change the code as:

```c++
// Using cursor position.

if (modifier & kModifierControl) // Line 772.
  setValueAt(left, defaultValue[left]);
else if (modifier & kModifierShift)
  setValueAt(left, snap(1.0f - double(mousePosition.getY()) / getHeight()));
else
  setValueAt(left, 1.0f - double(mousePosition.getY()) / getHeight());
```

or,

```c++
// Using anchor position.

if (modifier & kModifierControl) // Line 772.
  setValueAt(left, defaultValue[left]);
else if (modifier & kModifierShift)
  setValueAt(left, snap(1.0f - double(anchor.getY()) / getHeight()));
else
  setValueAt(left, 1.0f - double(anchor.getY()) / getHeight());
```

My impression was that using cursor position was unintuitive, and using anchor position wasn't expressive when the number of bar is low. So I came up with current behavior.

Which one do you prefer?

**Comment by mxmilkiib** [comment]
I prefer the second one.

**Comment by ryukau** [comment]
Changed behavior to use anchor point in latest commit.

If it's not working correctly, add a comment to this issue. I'll reopen.
