### ISSUE TITLE
CV plugins?

### ISSUE THREAD

**Issue by mxmilkiib** [ryukau/LV2Plugins#3]
Might you at all be interested in creating plugins that utilise the [CV port system of LV2 and JACK](https://linuxmusicians.com/viewtopic.php?f=1&t=20701)? Anything from the very modular to larger multi-oscillator-and-fx scale plugins would be welcome if you were.

**Comment by ryukau** [comment]
Is there some example plugin which is using CV port option with DPF?

**Comment by mxmilkb** [comment]
https://github.com/BramGiesen/cv-lfo-blender-lv2

**Comment by ryukau** [comment]
Thanks for the information. I'll look into it.

**Comment by mxmilkb** [comment]
Just tried the new plugins, wow, very nice, ty :) If you might at all need any inspiration, [here](https://github.com/mxmilkb/carla-modular-synth-tests/issues/2) are a few notes I've made.

**Comment by ryukau** [comment]
Thanks for trying out. I added some more plugins. I'll look into the issue you linked later. A huge limitation I noticed is that CV port plugins can't make a feedback loop at least on Carla.

For the record, building CV port plugins requires [rdflib](https://rdflib.readthedocs.io/en/stable/).

**Comment by ryukau** [comment]
Added 2 slew limiters.

CV_PController is exponentially weighted moving average filter (described in [here](https://dsp.stackexchange.com/a/54088)).

CV_RateLimiter is based on [description](https://www.mathworks.com/help/simulink/slref/ratelimiter.html) found on mathworks.com.

**Comment by mxmilkb** [comment]
Loving it, thanks :)

![image](https://user-images.githubusercontent.com/108225/77568851-2f540380-6ec1-11ea-9103-71293b9ef812.png)

**Comment by mxmilkb** [comment]
To note, direct CV->audio patches are only possible in Carla with the JACK multi-client engine mode.

**Comment by falkTX** [comment]
> To note, direct CV->audio patches are only currently possible in Carla with the JACK multi-client engine mode.

Note this is actually a bug, carla should not be allowing this.

**Comment by ryukau** [comment]
Added CV_3PoleLP. This sounds very similar to Fast LP in FL Studio.

**Comment by ryukau** [comment]
Added 3 more plugins.

CV_DoubleFilter is a 4-pole filter. This filter is linear, but parameter tuning is weird.

CV_HoldFilter is a decimator combined with resonance filter. PolyBLEP residual is used to suppress aliasing. Note that it causes latency when using PolyBLEP residual.

CV_RampFilter is similar to CV_HoldFilter, but interpolates by line instead of step function.

**Comment by tank-trax** [comment]
@mxmilkb have you tried [Ingen](https://drobilla.net/software/ingen)?

**Comment by mxmilkb** [comment]
Yes, the graph canvas is pretty, though it has various rough edges and isn't seeing development at the moment as drobilla is atm focusing on pugl and lv2, so I prefer to use Carla. Synthpod is another notable host with graph routing.

**Comment by mxmilkb** [comment]
@ryukau Would it be possible to make an ADSR envelope that is CV controlled? Like the AMS VC Envelope. Or at least that have a gate and trigger like ZLFO?

Maybe more like ZLFO though, because AMS VC Envelope doesn't 'latch' what comes in the ports as a property, i.e. its cannot be set from the Carla edit dialog window (not unless falktx implements optional manual CV input editing in Carla, so one can control CV port values as if they were control properties, something we have discussed in #lad). ZLFO properties can just be exposed as CV in Carla.

Reset and auto-looping (to blur the line between LFO/OSC/ADSR - see the Joranalogue contour 1 video) would also be incredible if possible. Possibly maybe even an DAHDSR?

**Comment by ryukau** [comment]
I'll try AMS and ZLFO envelopes to see how they behaves.

Is DAHDSR typo of AHDSR? If it's not, I'd like to know existing module/plugin using DAHDSR.

**Comment by mxmilkb** [comment]
There are two [DAHDSR](https://d2wclktjr2mmlu.cloudfront.net/media/wysiwyg/articles/learning-synthesis-envelopes-1/DAHDSR-2.jpg) envelopes in [omins.lv2](http://git.drobilla.net/cgit.cgi/omins.lv2.git/tree/omins.lv2) and one in [blop.lv2](https://gitlab.com/drobilla/blop-lv2/-/blob/master/blop.lv2/dahdsr.ttl).

I am still learning the AMS envelopes, though I've just changed two to two ZLFO instead, for longer envelopes and more control.

(FYI, two ZLFO issues; a) the custom waveform, if node 2 is the same horizontal position as node 1, the output FUBARs, b) ZLFO doesn't have a one-shot trigger non-freewheel feature ([yet](https://redmine.zrythm.org/issues/1447)), so I set a slow ~0.2 speed with an envelope for one quarter width of the waveform, and it gets retriggered to the start again before it would naturally freewheel loop).

**Comment by ryukau** [comment]
Thanks for the explanation. I thought first D as also decay.

Would you elaborate on non-latch behavior on AMS VC Envelope? I read the code, but wasn't sure which parameter you are talking about.

**Comment by mxmilkb** [comment]
In a properly modular sense, the unit only knows the values for its envelope stages when they are actively being fed into it.

Some modules/hosts have a memory to 'latch' the last value that was passed in. That includes using parameters exposed as CV ports in Carla, or using the state in the Control->CV plugin. (I have make a suggestion about making that optionally available for all CVPorts https://github.com/falkTX/Carla/issues/1076)

Also, the LV2 Parameters spec notes DAHDSR envelopes http://lv2plug.in/ns/ext/parameters/#EnvelopeControls

**Comment by ryukau** [comment]
Thanks for additional information. I got the idea from the issue you opened on Carla repository.

I don't think DPF provides a method to detect a port is disconnected. So I can't implement latching for now. Also in my opinion, the latch functionality is better provided by host for consistent user experience.

**Comment by ryukau** [comment]
Added CV_ExpLoopEnvelope. This envelope has 8 sections for loop. It can outputs tone, but tuning may be required. For more information, see [`lv2cvport/README.md`](https://github.com/ryukau/LV2Plugins/tree/master/lv2cvport#cv_exploopenvelope).

Currently, CV_ExpLoopEnvelope is not tested extensively. So if you find bug, please report it.

**Comment by mxmilkb** [comment]
Wow! Trying it out now.

If there were maybe a [bend control](https://www.youtube.com/watch?v=wsd8hDgo2O4&t=205) for each stage, that would for waveform shaping.

I like how right-click on a button cycles between min and max. Might it be possible if middle-click (or something) could set a value in the middle of the range? So that Level can be set to 0.

**Comment by ryukau** [comment]
Thanks for feedback. Changed right click to cycle between min/mid/max.

The algorithm used for CV_ExpLoopEnvelope is fast, but not suitable to change curve type. I leave DSP part of CV_ExpLoopEnvelope as it is, and will make one with curve control after finishing other things.

**Comment by mxmilkb** [comment]
Also, thank you for CV_Gate16. It's much more practical than AMS CV Source or multiple Control->CV plugins!

Possibly could each channel get a mute and possibly solo button?

Maybe harder, but if Trigger/Gate/DC could be set individually for each channel?

Beyond that; being able to set/save/recall names for each channel, including maybe actually altering the output port names, would be killer, but tbh I don't understand if and how DPF and LV2 might allow that, but that's just a further thought, no worries if it's not workable :) Cheers again!

**Comment by ryukau** [comment]
In DPF, there's no easy way to change LV2 port names while plugin is running. Also I'm not sure if LV2 allows user to rewrite port properties for different instances.

For reference, port properties are written in `plugin.lv2/plugin_dsp.ttl`. It looks like this:

```ttl
    lv2:port [
        a lv2:OutputPort, lv2:CVPort ;
        lv2:index 4 ;
        lv2:symbol "output" ;
        lv2:name "Output" ;
    ] ;
```

`lv2:name` is the port name. `lv2:symbol` is internal name and changing this breaks compatibility.

I'll implement rest of suggestions when I get time. I think adding delay for each output is also useful.

**Comment by ryukau** [comment]
Updated CV_Gate16.

- `type` is now available for each output.
- `delay` is added for each output.

Note that delay counter resets for each note-on, so trigger signal may not output when delay time is greater than 0.

For example, consider a type is set to `Trigger` and a corresponding delay is set to 0.5 seconds, and first note-on comes in. If another note-on comes in 0.1 seconds after first note-on, first impulse will be appear at 0.6 seconds after first note-on.

**Comment by ryukau** [comment]
Added CV_PolyLoopEnvelope. This envelope has curve control for each section.

**Comment by mxmilkb** [comment]
Amazing stuff :)

Waveform rendering issue; when the UI is closed then reopened, the curves have turned into straight lines. Altering any of the curve values makes the waveform redraw with the correct curves.

**Comment by ryukau** [comment]
Thanks for the catch. Redraw issue is fixed.

I'll look into the issue on the edit later. This narrowing bug appears when:

- Entire envelope is short.
- Loop End is set to 8.
- Section 0 decay, hold, or level is not 0.

**Comment by mxmilkb** [comment]
Am I right in thinking the CV inputs aren't working yet? I cannot change the Gain or a Decay from CV_Gate16 etc.

Hmm, whenever I try to rename CV_PolyLoopEnvelope in Carla, Carla freezes up.

**Comment by mxmilkb** [comment]
I made a [short test video](https://www.youtube.com/watch?v=L3sP3EE7BVQ).

**Comment by ryukau** [comment]
I pushed fix for the bug. There was a serious mistake that access out of bounds of array. 

I could rename CV_PolyLoopEnvelope without problem on Carla.

**Comment by ryukau** [comment]
CV inputs of CV_PolyLoopEnvelope are working, but CV_Gate16 had a bug that gate signal stops immediately after note-on. This is also fixed now.

Note that Gain CV port value will be added to the UI Gain value. So when using Gain CV port, I recommend to set UI Gain value to 0.

**Comment by mxmilkb** [comment]
I was trying with DC mode. [Here's a very short demo video](https://www.youtube.com/watch?v=DhW5Dj5vmVE).

**Comment by ryukau** [comment]
CV value do not update UI value. They are independent in my plugins.

**Comment by mxmilkb** [comment]
I made a [video](https://www.youtube.com/watch?v=seLMOQ6HiBM) with LFOd curves for a morphing waveform.

**Comment by ryukau** [comment]
Added CV_DelayLP3. Beware that resonance may blow up output.

**Comment by mxmilkiib** [comment]
I've not been looking much at synth things recently (doing some life things plus thinking about how to sequence things) but I'll swing back soon.

Might it be possibly to request also 2 and 4 section variants of CV_PolyLoopEnvelope?

**Comment by ryukau** [comment]
Added CV_PolyLoopEnvelope2/4.

I'm not sure about usefulness of CV_PolyLoopEnvelope2. At least it works as ordinary AD envelope.

**Comment by mxmilkiib** [comment]
I'm using CV_PolyLoopEnvelope2 for drum envelopes.

![image](https://user-images.githubusercontent.com/108225/82142027-63003980-9831-11ea-9d70-93295bae6100.png)

But with the decay and hold of both sections, there is still an envelope, as above. (yes, they are the right way around)

I also saved and restarted, now changing the decay amount a very small bit makes the curve very big very quickly;

![image](https://user-images.githubusercontent.com/108225/82142225-ac04bd80-9832-11ea-84b9-919f9f66c2ef.png)

I'm not sure what's happening with the second one there either :)

**Comment by mxmilkiib** [comment]
This is fairly confusing:

![image](https://user-images.githubusercontent.com/108225/82142483-91cbdf00-9834-11ea-9668-c6d7ec5a2f61.png)

**Comment by ryukau** [comment]
I fixed a bug in envelope view.

When the total length of envelope was set to 0, the internal sampling rate for envelope view became +inf because of 0 division.

Also envelope has 2 additional sections internally (release and terminated). In some cases, it somehow went through these additional sections and added unnecessary information. That's the reason it was displaying magical section 2 and 3 in CV_PolyLoopEnvelope2.

I'm not sure if this is the bug you described, so please let me know if I'm missing something.

Just to make sure, even if decay and hold are set to 0, PolyLoopEnvelopes output at least 1 frame for each section. To check this behavior, change the scale of oscilloscope to around 200 μs.

**Comment by mxmilkiib** [comment]
I have rebuilt, and things seem OK now. I realise now that "changing the decay amount a very small bit makes the curve very big very quickly" is expected and only natural - the graph scale is changing, as noted by the numbers, it is simply that the graphic of the curve stays the same, which is slightly confusing if one naively expects the curve to look different with a different decay length :)

**Comment by mxmilkiib** [comment]
Actually, is the gain of the output might be higher than it should be? I what happens in sisco.lv2 is that anything above 1.0 gets rendered as being clipped at 1.0.

![image](https://user-images.githubusercontent.com/108225/82252865-ba90c900-9947-11ea-8463-ce897bc66464.png)

**Comment by ryukau** [comment]
Which color in oscilloscope is the output of PolyLoopEnvelope?

Also it looks like CV signal is supplied to PolyLoopEnvelope's gain port. In this case, CV value is added to UI value. So it's possible to exceed 1.0.

When the UI gain value is set to 0, envelope view displays "CV Gain Ready" text. Just in case, right click can be used to set UI value to 0.

The wording is a bit unclear, but I've already documented this behavior in [lv2cvport/README.md](https://github.com/ryukau/LV2Plugins/tree/master/lv2cvport#cv_exploopenvelope). See CV_ExpLoopEnvelope -> Decay, Hold, Level section. Documentation of CV plugins is in ad-hoc state. So any suggestion or improvement is welcome.

**Comment by mxmilkiib** [comment]
It's the red. Aaah, right. I see the CV Gain Ready now, thanks!

**Comment by mxmilkiib** [comment]
Here is my drum machine setup right now;

![image](https://user-images.githubusercontent.com/108225/82337266-7eab4180-99e3-11ea-920c-8d0a6ec830dd.png)

I'll be adding more instrument channels, but I think the big challenge is figuring out sequencing (and looping). I would really like to avoid MIDI. An Ableton/Bitwig-like scene/clip launch style seems like it would make most sense. I have used [sequencer64](https://github.com/ahlstromcj/sequencer64) for MIDI looping before, but there is nothing with as versatile MIDI bindings that also does audio ([Giada](https://github.com/monocasual/giada), [Luppp](https://github.com/openAVproductions/openAV-Luppp)). [Ossia](https://github.com/OSSIA/score/issues/982) is one future possibility, and I think Alex of [Zrythm](https://www.zrythm.org) will add CV features in the future. I've also [asked]the developer of [BSEQuencer](https://github.com/sjaehn/BSEQuencer/issues/20) if they might be interested.

**Comment by sjaehn** [comment]
It would be a lot of work to make a CV version of a typical MIDI tool, like a polyphonic sequencer. And it feels a bit like to roll back the time ;-)

But FYI, I'm busy with adding a CV output to B.Shapr.

**Comment by mxmilkiib** [comment]
BTW, thank you @ryukau, and @sjaehn and @falktx, so incredibly much :)

@ryukau Maybe time to close this issue? Up to you.

**Comment by ryukau** [comment]
@mxmilkiib Thanks for your ideas.

I'll close this issue. If you come up with another idea, feel free to open issue.
