### ISSUE TITLE
CV_Gate16: ctrl-shift-drag to lock multiple bars doesn't lock last bar

### ISSUE THREAD

**Issue by mxmilkiib** [ryukau/LV2Plugins#35]
So If I hold ctrl+shift and right-click drag from the first bar all the way over beyond the right edge of the window, the last bar does not get locked;

![image](https://user-images.githubusercontent.com/108225/88235186-3c67e000-cc72-11ea-8f46-5b5dc82cb7d1.png)

**Comment by ryukau** [comment]
Thanks for the report. Fixed in latest commit (75cf9cd).
