### ISSUE TITLE
CV_PolyLoopEnvelope: overlapping envelopes?

### ISSUE THREAD

**Issue by mxmilkiib** [ryukau/LV2Plugins#36]
Not so prominent in [this video](https://www.youtube.com/watch?v=L3SCrneBGUQ) due to compression, but an overlapping note envelope can make the signal snap straight back to 0 from the previous note envelope, creating an undesired pop.

The [poly synth](https://user-images.githubusercontent.com/108225/88303501-00c72780-ccff-11ea-87a1-a17ab3b30b13.png) has 10 channels now, to cope with more than one note played at the same time. Might the solution be to add more channels, or could the behaviour of the envelope generator be altered so that the first envelope follows/flows through into the next?

**Comment by ryukau** [comment]
I tested, but couldn't reproduce it. Isn't the time of some sections set to 0?

When triggered while active, CV_PolyLoopEnvelope starts the new section from the last value of previous section. This kind of pop noise shouldn't occur unless the user intentionally set to do so.

**Comment by mxmilkiib** [comment]
The second section is 0'd out, apart from the value which is 1 to match the section before.

I'm also confused about this; if the gate signal in goes to 0, should the envelope not move to the release phase, i.e. move directly beyond section 3? But it does not do this with the first gate in here;

![image](https://user-images.githubusercontent.com/108225/88349321-9dadb300-cd47-11ea-8f46-a7d314558a45.png)

If I slightly raise the level of Section 0 in the GUI;
![image](https://user-images.githubusercontent.com/108225/88349771-e7e36400-cd48-11ea-907b-9280d81881f1.png)

Now I'm at this point, I need to learn more to be able to tell if it's my own mistake :)

**Comment by ryukau** [comment]
On image, try turning up the channel 0 of CV_Gate16 to set the section 0 time to non 0. It should reduce pop noise at gate on.

When triggered, envelope starts from section 0. So, if the time of section 0 is set to 0, it immediately resets to the section 0 level.

When loop end is set to max, envelope goes through the entire section after gate on, or more precisely, signal goes from 0 to 1. It's called trigger mode in [documentation](https://github.com/ryukau/LV2Plugins/tree/master/lv2cvport#cv_exploopenvelope). Is this what you are asking?

**Comment by mxmilkiib** [comment]
Thanks, I understand better some of the previous lack my understanding and nuance of request now :)

AFAIU; with non-looping gated envelope, when the gate goes up to 1, the envelope outputs the level from the start until it gets to the sustain point, which it holds at until gate off, then the release phase is played. [Here](https://youtu.be/wsd8hDgo2O4?t=267) is the related Contour One behaviour.

A looping gated envelope is one that is self-driven and can function as an oscillator, which is Contour One with the switch set to Loop rather than Slew and how the current 'gated' behaviour works in CV_PolyLoopEnvelope.

**Comment by ryukau** [comment]
At gate on, CV_PolyLoopEnvelope decays from the last output value to the section 0 level. In other words, attack time shouldn't set to 0 in order to avoid pop noise. That's the reason loop start of CV_PolyLoopEnvelope (the one has 8 section) defaults to section 1. If you care about pop, I'd recommend to set loop start always at 1, and use section 0 for attack. And/or always insert slew limiter, lowpass filter or high shelving filter after CV_PolyLoopEnvelope, because it doesn't have mechanism to smooth edges.

Are these answer solved that the issue on the first post?
