### ISSUE TITLE
Makefile directives for building just one target format?

### ISSUE THREAD

**Issue by mxmilkb** [ryukau/LV2Plugins#5]
Currently LV2, VST and JACK versions of each plugin are generated on `make`. Could options `make all`, `make lv2`, etc. be possible?

**Comment by ryukau** [comment]
I added options for it. If it doesn't work, feel free to reopen this issue.

```bash
cd LV2Plugins
make -j LV2=false             # Disable LV2 build.
make -j JACK=false VST2=false # Disable jack and vst2 build.
```

Note that disables everything still runs compiler for some source code.

```bash
# Builds no plugins, but some DSP codes will be compiled.
make -j LV2=false JACK=false VST2=false
```

**Comment by mxmilkb** [comment]
Thanks! I've added the plugin set to the [AUR](https://aur.archlinux.org/packages/uhhyou.lv2-git).

**Comment by mxmilkb** [comment]
Would it be possible to run `generate-ttl.sh` as part of the LV2 build process?

**Comment by mxmilkb** [comment]
Also, I think, as it stands, the DPF code is still getting compiled for use in contexts set to false;

```
Compiling DistrhoPluginMain.cpp (JACK)
Compiling DistrhoUIMain.cpp (JACK)
Creating JACK standalone for d_info
Compiling DistrhoPluginMain.cpp (LV2)
Creating LV2 plugin library for d_info
Compiling DistrhoUIMain.cpp (LV2)
Creating LV2 plugin UI for d_info
Compiling DistrhoPluginMain.cpp (VST)
Compiling DistrhoUIMain.cpp (VST)
Creating VST plugin for d_info
```

**Comment by ryukau** [comment]
I fixed makefile.

1. Moved generate-ttl rule from `make install` to just `make`.
2. Disabled to build DPF example plugins.

Could you test it?

Also many thanks for packaging to AUR.

**Comment by mxmilkb** [comment]
That has done it :)

**Comment by ryukau** [comment]
Thanks for testing.
