### ISSUE TITLE
warnings during build

### ISSUE THREAD

**Issue by tank-trax** [ryukau/LV2Plugins#6]
OS: Debian Buster

not sure if this is an issue or innocuos but this warning repeats frequently during building

```
dsp/../../../common/dsp/../../lib/vcl/vectorf128.h:2093:100: warning: optimization attribute on ‘Vec2d round(Vec2d)’ follows definition but the attribute doesn’t match [-Wattributes]
 static inline Vec2d round(Vec2d const a) __attribute__((optimize("-fno-unsafe-math-optimizations")));
```
followed by

```
dsp/../../../common/dsp/../../lib/vcl/vectorf128.h:1186:21: note: previous definition of ‘Vec4f round(Vec4f)’ was here
```

**Comment by ryukau** [comment]
The warning comes from vector class library (VCL). Unless the plugin crash with segfault or illegal instruction, I think it's fine.

I once got similar warning while developing, but currently the warning disapeared in my environment. Updating VCL might remove the warning. Try `git submodule update --remote --merge`.

If it doesn't work, g++ version might be the cause. I'm using g++ 9 on Fedora, but it seems like Debian buster provides g++ 8 for now.

```bash
$ g++ --version
g++ (GCC) 9.3.1 20200317 (Red Hat 9.3.1-1)
```

- [Debian -- Details of package g++ in buster](https://packages.debian.org/buster/g++)

**Comment by tank-trax** [comment]
yep I am at

g++ --version
g++ (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by tank-trax** [comment]
yes I am at

```
g++ --version
g++ (Debian 8.3.0-6) 8.3.0
```

**Comment by tank-trax** [comment]
`git submodule update --remote --merge` did update but same warnings when compiling

Thanks
