### ISSUE TITLE
Sans font for GUI

### ISSUE THREAD

**Issue by KottV** [ryukau/LV2Plugins#8]
Hi, ryukau

I'd like to change the font in the LV2 plugins to the same family as in VST version.
There is TinosBoldItalic.cpp contains font glyphs, but I haven't found way to generate such c++ code from ttf.

**Comment by ryukau** [comment]
Hi, Kott.

I used `lib/DPF/utils/res2c.py` to create source code from a font file. I forget the exact command, but following might work:

```bash
mkdir resource
cp path/to/font.ttf resource
python3 res2c.py SomeNamespace resource
```

DPF provides `createFontFromFile()` method, which has a filename argument. So perhaps it's possible to configure font. I'll look into it.

- [DISTRHO Plugin Framework: NanoVG Class Reference](https://distrho.github.io/DPF/classNanoVG.html#a202e31bed7a83c59d417fa016f66f12a)

**Comment by KottV** [comment]
It works, thank You!

**Comment by ryukau** [comment]
Added `fontPath` option to style jsons.

`fontPath` must be absolute path to `*.ttf` file. When relative path is set, I'm not sure where the root directory is.

It seems like NanoVG doesn't work well with some `*.ttf`. If `fontPath` is set and GUI doesn't open, please try other font.

For more details, See: https://github.com/ryukau/LV2Plugins/blob/master/style/ColorConfig.md#font

**Comment by KottV** [comment]
Great! Thank You.
